version: "3"
services:
  node:
    image: "node:8"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - /var/run/docker.sock:/var/run/docker.sock 
    expose:
      - "3000"
    command: "npm start"